---
title: "Mini-Project 2"
author: "Emma King and Tasaday Green"
date: "October 31, 2017"
output: html_document
---


## Loading the data


```{r, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}
contributions %>%
  select(transaction_type) %>%
  group_by(transaction_type) %>%
  summarise(N = n())
```

```{r}
contributions2<-contributions %>% 
  select(transaction_type, transaction_dt, transaction_amt, cand_id) %>%
  filter(transaction_type == "24A")
contributions2
```

```{r}
ggplot(contributions2, aes(x = transaction_dt, y = transaction_amt)) +
  geom_point()
```
```{r}
candidates2<-candidates %>%
  select(cand_id, cand_party_affiliation) 

```
```{r}
join_contributions2_candidates2<- full_join(candidates2, contributions2, by = "cand_id") %>%
  filter(transaction_type == "24A", cand_party_affiliation == "REP" | cand_party_affiliation == "DEM") 
join_contributions2_candidates2
```
```{r}
join_contributions2_candidates2 %>%
  select(cand_party_affiliation) %>%
  group_by(cand_party_affiliation) %>%
  summarise(N = n())
```
```{r}
ggplot(join_contributions2_candidates2, aes(x = transaction_dt, y = transaction_amt, col = cand_party_affiliation)) + 
  geom_point() + xlab("Transaction Date") + ylab("Transaction Amount")
  
  
```
